# SPDX-License-Identifier: Apache-2.0

"""T4 property test for DIAG-09 -- DIAG-09's declared tier (`LOOPS.md`) is
T4, which subsumes the T3 differential file
(`tests/differential/test_client_hardening.py`), not replaces it. Mirrors
DIAG-02's own `test_uds_client_properties.py`'s relationship to
`test_uds_client.py`.

One property: an NRC byte, generated by `hypothesis` across the full
0x00-0xFF range rather than the handful of values this codebase's own
constants (`NRC_REQUEST_OUT_OF_RANGE`, etc.) happen to name, always
translates to a `NegativeResponseException` whose `.response.code` matches
-- no crash, no hang, no silently-swallowed or mistranslated value.

The ECU/client pair is set up once via a module-scoped fixture, not per
example -- constructing a fresh vcan-bound client per example would make
this tier prohibitively slow (same rationale as
`test_uds_client_properties.py`). `Scenario.failure_injections` is read
live per-request by the responder (`ProtocolState.matching_injection`),
so each example mutates it in place rather than rebuilding the ECU.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from udsoncan.client import Client
from udsoncan.exceptions import NegativeResponseException

from tapwright.diag.uds_client import open_uds_client
from tapwright.diag.virtual_ecu import DIDConfig, FailureInjection, Scenario, VirtualECU
from tapwright.hal import open_bus

pytestmark = pytest.mark.requires_vcan

TEST_DID = 0x1234
RDBI_SID = 0x22

SKIP = pytest.mark.skip(reason="test plan — implementation pending (issue #35)")


@pytest.fixture(scope="module")
def hardened_client(vcan_channel, raw_did_codec) -> Iterator[tuple[Client, Scenario]]:
    scenario = Scenario(dids={TEST_DID: DIDConfig(value=b"\x01")})
    bus = open_bus(backend="socketcan", channel=vcan_channel)
    try:
        with VirtualECU(scenario, channel=vcan_channel):
            client = open_uds_client(
                bus,
                rxid=scenario.response_id,
                txid=scenario.request_id,
                config={"data_identifiers": {TEST_DID: raw_did_codec}},
            )
            with client:
                yield client, scenario
    finally:
        bus.shutdown()


@settings(deadline=None)
@given(nrc=st.integers(min_value=0x00, max_value=0xFF))
def test_any_nrc_byte_translates_to_a_matching_negative_response_exception(hardened_client, nrc):
    client, scenario = hardened_client
    scenario.failure_injections = [
        FailureInjection(service_id=RDBI_SID, selector=TEST_DID, kind="nrc", nrc=nrc)
    ]

    with pytest.raises(NegativeResponseException) as exc_info:
        client.read_data_by_identifier(TEST_DID)

    assert exc_info.value.response.code == nrc
